### ISSUE TITLE
What are the difference to Chalk?

### ISSUE THREAD

**Issue by deleonio** [marvinhagemeister/kolorist#6]
Hi,

can you briefly explain why there is kolorist? The chalk (https://github.com/chalk/chalk) project on this topic has been around for a very long time.

**Comment by marvinhagemeister** [comment]
Chalk does a lot more then just adding colors to terminal output. It comes with a light built in [template engine](https://github.com/chalk/chalk#tagged-template-literal), [color conversion pipeline](https://github.com/chalk/chalk#256-and-truecolor-color-support) and a bunch of other stuff that I feel are overkill for me. `kolorist` does only one thing: It just adds colors, nothing more, nothing less.

That difference comes to light if we compare package sizes and the number of dependencies that have to be fetched on install:

| Package | Size | dependencies |
|---|---|--:|
| chalk | [20.4kB](https://bundlephobia.com/result?p=chalk@4.1.0) | 5 |
| kolorist | [3.3kB](https://bundlephobia.com/result?p=kolorist@1.3.2) | 0 |

I'm currently in the process of making node docker containers lighter at work and there isn't one single piece that makes it large, it's rather more like a death by a thousand papercuts. Lib A adds 30kb unnecessary stuff (for me) here, another lib A adds 30kb there, and pretty soon those libs add up to a few MBs on disk.

Another reason why I made `kolorist` is that it's simply fun to strip down concepts to the bare essentials. It's kinda a hobby of mine.

If you don't mind the weight or share the same constraints that I have, you can just pick whatever project you prefer. In the end both give you colored terminal output.

**Comment by deleonio** [comment]
Many Thanks,

for your detailed explanation.

You may have noticed by now, but in another case I'm following the same philosophy with the @leanupjs project.

I want to offer a complete technology stack for developing SPAs that has as few dependencies as possible and yet is fully functional.

I can only offer almost all frames in the same shape with a flat frame facade.

The topic is particularly important in sensitive organizations.

- [ ] We'll replace Clark with Colonist. (https://github.com/leanupjs/leanup/issues/1350)

**Comment by deleonio** [comment]
Thank you @marvinhagemeister,

for your detailed explanation.

Maybe you've already read it, but in another case, I'm following the same philosophy with the @leanupjs project.

I want to offer a complete technology stack for developing SPAs that uses as less dependencies as possible and yet is fully functional.

If at all necessary, I can use a small framework facade to provide the stack to all frameworks in the same form. (only needet for dev and build)

The topic is particularly important in sensitive organizations.

For example, I can implement fully automated dependency updates to counter emerging vulnerabilities.
